### PR TITLE
Listen and Speech addon

### PR DESCRIPTION
**Pull request by darylfung96**
requirements:
pip install pyttsx3 # for python 3
or
pip install pyttsx # for python 2

pip install SpeechRecognition
pip install pyAudio

Currently, the speech recognition needs to communicate with google server, it may be slow when waiting for the bot to respond. But I will try and find a way to make it the speech recognition offline.

### CODE REVIEW

**Comment by darylfung96** [comment]
Yeapp sure I could change that.

**Comment by darylfung96** [comment]
Alright, I added a conversation.py for the listen and speech instead of putting them inside console.

**Comment by sprinteroz** [comment]
> Currently, the speech recognition needs to communicate with google server, it may be slow when waiting for the bot to respond. But I will try and find a way to make it the speech recognition offline.

Wow I have just been looking into the basics of doing this and was going to try and learn or should I say just wing the code. lol.

 Now I have found a script that can be used instead of  of google server, it is a JavaScript code so it would be easy to call on the pc also there is a paid version of this  JavaScript for company use.

The git hub link to the old file is here that can be modified: []github.com(https://gist.github.com/anchetaWern/ed6e841555602656e6ae)

You can use the new updated file for free use only unless you pay :
[] API(https://responsivevoice.org/api/)
[]Script( http://code.responsivevoice.org/responsivevoice.js)

**MUST READ Latest version 1.5.2 licence** even if you want to use this version free []responsivevoice.org license/(https://responsivevoice.org/license/)

Hope this helps you out

**Comment by darylfung96** [comment]
Oh. The part where it needs to communicate with Google server was just the speech recognition. The voice that comes out is from the computer itself though. But still thanks for sharing!

**Comment by sprinteroz** [comment]
OK NP I just found these 2 dependencies, do not know if they will help speed things up at all,   

Create an mp3 file from spoken text via the Google TTS (Text-to-Speech) API
https://pypi.python.org/pypi/gTTS

Calculates a token to run the Google Translate text to speech
https://pypi.python.org/pypi/gTTS-token

**Comment by darylfung96** [comment]
Okay @sprinteroz , thanks for the recommendations :)

The speech recognition is now offline supported. Added some calibaration for microphone and support for linux as well.

For linux, need to install:
sudo apt-get install pulseaudio libpulse-dev swig

**Comment by keiffster** [comment]
Ok, I am going to start merging this in over the next few days since I have finished adding the regex tag and debugging help features

**Comment by keiffster** [comment]
I've merged in the changes but in a very different way to the way you might expect.
I have spun out a separate client [Talk-Y](https://github.com/keiffster/talk-y) as a separate repo and refactored the code to allow dynamic selection via config of Text To Speech and Speech To Text engines

The reason for the separate repo is
1. The number of dependencies increase significantly and are only relevant if you want that client
2. On OSX PyTTS does not work when installed from Pip and needs to be installed from source which I have yet to document, but I have added OSXTTS which uses native 'say' command to speak via the OSX native speech system

**Comment by darylfung96** [comment]
Okay @keiffster . I will close this pull request then since the changes have been merged.

Cheers,

Daryl Fung

**Comment by keiffster** [comment]
No problems, your ideas are making it into the core product

talk-y is turning in to a very interesting Alexa, Siri, Cortana type project

And random responses is just about to go into the core product

**Comment by darylfung96** [comment]
That's awesome. I'm glad that your project is growing and that we could be of some help in contribution to you. 🙂

**Pull request closed without merging**
