### PR TITLE
Added... Windows Command Prompt Code, Github Clone address, Website Info address. 

### PR DESCRIPTION
**Pull request by sprinteroz**
Added... Windows Command Prompt Code, Github Clone address, Website Info address. 
[requirements.txt](https://github.com/keiffster/program-y/files/1240661/requirements.txt)

I have added all the links need for people to quickly find the files needed to run Program-y e.g. 
Windows Command Prompt Code: 
 Github Clone: 
 Website Info: 
also some tips for windows users

### CODE REVIEW

**Comment by sprinteroz** [comment]
Sorry did not want the NATHAN file in the pull request are you able to delete that file at all if you merge the file?

**Comment by keiffster** [comment]
Hi, 

I think you may have misunderstood the purpose of requirements.txt. This is not a documentation file, rather a control file for pip 

This file allows you to install all dependencies with a single command, e.g.
```
pip install -r requirements.txt
```
Worth taking a look at [Requirements files](https://pip.readthedocs.io/en/1.1/requirements.html) for more information

However you have done a great job of documenting the dependencies and so I'll add the information to the wiki instead

**Comment by keiffster** [comment]
Added to wiki

https://github.com/keiffster/program-y/wiki/Python_Dependencies

**Comment by sprinteroz** [comment]
Hi thanks for clearing that up for me @keiffster , I used the command 
`pip install -r requirements.txt`
I found after I I run it that I would of needed to install 18 more dependencies to get the program to work, the manual way I was doing it.  Would you like me to do up the  Windows Command Prompt Code: Github Clone: Website Info:

I could label the following dependencies as "manual dependencies install if not using command `pip install -r requirements.txt` "

Jinja2  2.9.6
MarkupSafe 1.0
Werkzeug 0.12.2
astroid 1.5.3 
certifi 2017.7.27.1 
chardet 3.0.4 
click 6.7 
colorama 0.3.9 
idna 2.6 
isort 4.2.15 
itsdangerous 0.24 
lazy-object-proxy 1.3.1 
mccabe 0.6.1 
oauthlib 2.0.2 
requests-oauthlib 0.8.0 
six 1.10.0 
urllib3 1.22 
wrapt 1.10.11

These are the ones we already have on the wiki now
*sleekxmpp 1.3.2 
*tweepy 3.5.0 
*wikipedia 1.4.0 
*pyyaml 3.12 
*requests 2.18.4
*pylint 1.7.2 
*python-dateutil 2.6.1 
*nose 1.3.7
*lxml 3.8.0 
*flask 0.12.2 
*coverage 4.4.1 
*beautifulsoup4 4.6.0

Also I will add the versions of files we are using at the moment if you like.

**Comment by keiffster** [comment]
Those are sub dependencies of the files referenced in requirements.txt and should in installed as part of those being installed through pip

Are you sure pip install completed successfully.

I noticed that you reference Python 2.7 in the notes, but Program-Y does not support Python 2, its only Python 3 compatible. Did you run the 3 version of pip or the 2 version

K

**Comment by sprinteroz** [comment]
> Those are sub dependencies of the files referenced in requirements.txt and should in installed as part of those being installed through pip
> 
> Are you sure pip install completed successfully.
> 
> I noticed that you reference Python 2.7 in the notes, but Program-Y does not support Python 2, its only Python 3 compatible. Did you run the 3 version of pip or the 2 version

I have python 3.5 and 3.6 on my computer all installed successfully.

**Comment by sprinteroz** [comment]
I did not want to go off topic with the new text to spech add on so i thought i would post this here so you can update the wiki  Python Dependencies : https://github.com/keiffster/program-y/wiki/Python_Dependencies

Files that are required to run Program-y

13.Pyttsx3
14.SpeechRecognition
15.PyAudio

=============================
Detailed Instructions

13.Pyttsx3

Installation: pip install pyttsx3
Github Clone: https://github.com/nateshmbhat/pyttsx3
Website Info: https://pypi.python.org/pypi/pyttsx3/2.6

14.SpeechRecognition

Installation: pip install SpeechRecognition
Github Clone: https://github.com/Uberi/speech_recognition
Website Info: https://pypi.python.org/pypi/SpeechRecognition/

15.PyAudio

Installation: pip install pyAudio
Github Clone: https://github.com/jleb/pyaudio
Website Info: http://people.csail.mit.edu/hubert/pyaudio/

Also I sent you a facebook request and google mail invite if you still use them.

**Pull request closed without merging**
